### ISSUE TITLE
Validate Smalltalk version

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/run-smalltalkci#10]
While setting up a new GitHub workflow today, I noticed that when you pass an invalid Smalltalk version such as `Trunk`, no direct error is raised for this argument but instead, the apt updates are not installed so that I end up with an uninformative `libpulse` error when running `smalltalkci` in a later step of the job:

```
/home/runner/.smalltalkCI/_cache/vms/Squeak64-Trunk/sqcogspur64linuxht/lib/squeak/5.0-202003021730/squeak: error while loading shared libraries: libpulse-simple.so.0: cannot open shared object file: No such file or directory
```

See this build for reference: https://github.com/hpi-swa-lab/SqueakByExample-english/runs/2124919496?check_suite_focus=true

Since the Smalltalk version needs to passed to both steps separately (unfortunately enough - couldn't this info be cached anywhere on the runner?), IMHO also both steps should validate it separately.

**Comment by fniephaus** [comment]
For the "libpulse-simple.so.0: cannot open shared object file: No such file or directory" error, I've opened https://github.com/actions/toolkit/issues/737.

**Comment by LinqLover** [comment]
Thanks for the fast solution!
