### ISSUE TITLE
Failed setup should fail build early

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/run-smalltalkci#11]
Sometimes, setup fails (e.g. when `apt-get update` fails) and that should fail the build immediately. Otherwise, users may be confused by another error masking the original problem.

Example: https://github.com/tom95/sandblocks/runs/2113675675#step:3:57

Blocked by https://github.com/actions/toolkit/issues/737

**Comment by LinqLover** [comment]
I think this can be closed because of a89a05efc1acb01977b6acf27bd1fa506cacaacb?
