### ISSUE TITLE
Smalltalk CI started to fail on Pharo 9 after version update to 1.3.5

### ISSUE THREAD

**Issue by Bajger** [hpi-swa/run-smalltalkci#23]
**Summary**
On Exercism Pharo project there was PR to update Smalltalk CI from 1.3.4. to 1.3.5. After that Pharo 9 build started to fail for some reason.

**Actual**
Smalltalk CI is failing for Pharo 9 build - when using 1.3.5 version. See this: 
But when merged with main, it stated to fail: https://github.com/exercism/pharo-smalltalk/actions/runs/3459413003
When PR was initiated, job runned ok: https://github.com/exercism/pharo-smalltalk/actions/runs/3415732854

**Expected**
Job runs ok for Pharo 9

**Details**
Probably it has something to do with: https://github.com/pharo-vcs/iceberg/issues/1426
So I'm not really sure how it is related to Smalltalk CI - probably just commit message was too long?

**Comment by Bajger** [comment]
@tinchodias: Can you advice, what could be a problem?

**Comment by tinchodias** [comment]
Hi, the error is `OmFileStoreReadingError`, which belongs to the Ombu or in fact Epicea project... I could check, but please confirm me: is it reproducible? I mean, does it happen each time the job in Pharo 9 is run?
In that case, I would try to run smalltalkci locally.

**Comment by Bajger** [comment]
How can I test Smalltalk CI locally? Is it something like following? 
- clone repo with Smalltalk CI
- Define Smalltalk.ston with Pharo 9 build and baseline definition
- what else?

**Comment by tinchodias** [comment]
Something like that. Check at: https://github.com/hpi-swa/smalltalkCI#how-to-local

**Comment by Bajger** [comment]
Hi! 
I was able to reproduce locally: 
reprosteps:
1. Clone repos: `gh repo clone hpi-swa/smalltalkCI` and `gh repo clone exercism/pharo-smalltalk`
2. created `.smalltalk-test.ston` with following contents and moved to `<path-to-repo>/exercism/pharo-smalltalk` directory:
```
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'Exercism',
      #directory : 'dev/src',
      #load : [ 'dev' ],

      #platforms : [ #pharo ]
    }
  ],

  #testing : {
    #include : {
      #packages : [ 'Exercism' ]
    },
    #exclude : {
      #classes : [ #AllExercismTests, #ExercismTest, #ExercismHttpClientTest ],
      #packages : [ 'ExercismWIP', 'ExercismTools', 'ExercismDev', 'ExercismSystemTests']
    }
  }
}
```
3. executed: `../smalltalkCI/bin/smalltalkci -s Pharo64-9.0 --headful ./.smalltalk-test.ston`

**Result**
![image](https://user-images.githubusercontent.com/45875448/203518404-2e483acf-481a-435b-848f-5aa60b00e7ea.png)

@hogoww Probably it has something to do with your changes here? https://github.com/hpi-swa/smalltalkCI/commit/b58ba5b309013ccf1d8623dac82d0e4eb69d2568
Thanks for looking at this!  
PS: I just realized, this issue should be moved to `hpi-swa/smalltalkCI`

**Comment by Bajger** [comment]
Contents of ombu file here: https://gist.github.com/Bajger/817c2ed60a0b5326e0e43ee5ab8c4d82

**Comment by hogoww** [comment]
With the default .smalltalk.ston it works well in headful / headless.
with a copy paste of your .smalltalk.ci, it does not
![Screenshot 2022-11-23 at 11 25 59](https://user-images.githubusercontent.com/21278554/203523722-41fa4ef7-a4db-4d4d-93d5-a373f203b4cb.png)
Has the git diff finds very little difference, could it be a problem of file encoding ?
What's your keyboard? 

Regardless, it does not look related to my changes.

**Comment by hogoww** [comment]
Okay, after a bit more debugging, this happens when there are no newline at the end of the file.
I can confirm that it's unrelated to me.
Not sure however how to fix it.

**Comment by Bajger** [comment]
So if I add a newline to the end, it will work?

**Comment by hogoww** [comment]
That has been what my testing said.

Other than that, that'd be cool if that wasn't a requirement for files, and particularly if they didn't throw a random error.

**Comment by Bajger** [comment]
Ok, I'll do more tests unrelated to Exercism. Will close this issue and open eventually for "P9 build fails when no new line at the end of ston file"

**Comment by Bajger** [comment]
Weird, I've tried again with freshly cloned repos (didn't touch the .smalltalk.ston at all) and this time it succeeded... I wasn't able to reproduce.

**Comment by tinchodias** [comment]
The ombu file looks corrupted! I don't remember to that error before. But if I understand well the conversation afterwards, you spotted the problem is unrelated to the ombu file. Right?

**Comment by hogoww** [comment]
From my local testing, it sounds like the bug happens only when the last character is not a newline.

**Comment by Bajger** [comment]
If I clone `exercism/pharo-smalltalk` repo, the last character in `.smalltalk.ston` file is newline, so it should not fail. So I don't understand, why it failed on GH. Maybe this is CR or CRLF problem?

**Comment by hogoww** [comment]
I don't know.
On the repo you linked, the next CI run on the same commit seem to have worked.
Are you sure you still have the problem to this day ?

**Comment by Bajger** [comment]
😄 This is really strange. CI is now green! 
![image](https://user-images.githubusercontent.com/45875448/203732556-917a571e-5348-433b-bf9f-a08894177405.png)

**Comment by Bajger** [comment]
Closing this issue. Cannot reproduce.

**Comment by Bajger** [comment]
Failed again :/ https://github.com/exercism/pharo-smalltalk/actions/runs/3539148418/jobs/5940730065

**Comment by fniephaus** [comment]
smalltalkCI uses Pharo's STON implementation to read the config file. I'm not sure what could be causing this problem, but it's probably not caused by smalltalkCI.

**Comment by hogoww** [comment]
> smalltalkCI uses Pharo's STON implementation to read the config file. I'm not sure what could be causing this problem, but it's probably not caused by smalltalkCI.

I agree with Fabio

**Comment by Bajger** [comment]
Might be, I've closed the issue now. Reason why I put it here was timing: PR with bumping from 1.3.4 to 1.3.5 started to fail on P9 on Mon, 14 Nov 2022 (exercism/pharo-smalltalk). 1.3.5. was updated week before: 2022-11-07. There were also some changes related to P9 on hpi-swa/smalltalk-ci project: 
![image](https://user-images.githubusercontent.com/45875448/203765759-e0383e5b-2d8b-4b5b-99d0-aa0d3fa10ed2.png)

So is it just coincidence?

**Comment by hogoww** [comment]
Don't know, I just know that it does not look related after looking at it :/

**Comment by Bajger** [comment]
No worries! Thanks for looking to this. I will need to do more investigation on that, find a triggering condition, since I wasn't able to reproduce it with newline in smalltalk.ston file. If I trigger error again, I will try with different project that can be loaded to P9. Part of the problem is that I don't know for what for OMBU files are used for and when they are created.

**Comment by hogoww** [comment]
> Hi, the error is `OmFileStoreReadingError`, which belongs to the Ombu or in fact Epicea project... I could check, but please confirm me: is it reproducible? I mean, does it happen each time the job in Pharo 9 is run? In that case, I would try to run smalltalkci locally.

As for when they are created, I'd think it's during the startup sequence.
Epicea is the tool that records your action to be able to reproduce them after a crash.
Also called "code changes" in the menu IIRC
