### ISSUE TITLE
Allow to configure smalltalkCI repo and version to use

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/run-smalltalkci#3]
The TravisCI integration allows to configure the smalltalkCI repo and version to use, this is very useful for testing changes before they land in the main repo. 
I'm proposing to add some optional inputs in the workflow allowing to set the BRANCH and REPO_URL to use.

**Comment by fniephaus** [comment]
Good idea! Do you want to give it a go, or shall I put this on my todo list? :)

**Comment by gcotelli** [comment]
I've just created a PR, so you can review it :)
