### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/run-smalltalkci#8]
I am getting warnings when using this action in multiple repositories:

> ## .github#L1
> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

It looks as if this repository might be (co-)responsible for this warning:

https://github.com/hpi-swa/setup-smalltalkCI/blob/35e0628253c55e8b78116869f541890a243d2ae8/dist/index.js#L1569-L1570

**Comment by fniephaus** [comment]
Thanks for raising this issue. Good to know they are deprecating `add-path`. It's a utility function provided by the core package. IIRC this workflow only uses it here:
https://github.com/hpi-swa/setup-smalltalkCI/blob/35e0628253c55e8b78116869f541890a243d2ae8/index.js#L55

**Comment by fniephaus** [comment]
As mentioned by the blog post, `@actions/core` required an update. @dependabot was so kind to open #6, so all that was left to do on our side was to repackage the action.

**Comment by LinqLover** [comment]
Great, thanks for updating! :-)
